### PR TITLE
Added chocolatey support

### PR DESCRIPTION
**Pull request by mawiseman**
I have added Chocolatey support to the project and already uploaded 1.0.1 successfully
https://chocolatey.org/packages/iishosts/1.0.1

If you accept this can you please 
- create a new release 1.0.2
- include the generated nupkg file there
- provide me with your chocolatey username so i can add you as a maintainer

Then I will upload 1.0.2 to chocolatey with
- 128x128 iishosts icon
- better looking description
- tags

thanks

### CODE REVIEW

**Comment by richardszalay** [comment]
Thanks for the PR! No problem - as long as I can remember how to build the installer ;)

**Comment by richardszalay** [comment]
I noticed there were a number of temporary files committed (eg. obj/Debug/project.razor.json). If that wasn't intentional, could you rebase them out of the PR?

**Comment by mawiseman** [comment]
done

**Comment by mawiseman** [comment]
@richardszalay are you happy with the changes?

**Comment by richardszalay** [comment]
Yeap, all good. The main issue with quickly getting a release out is actually building the project as it's compiled against IIS 7 for compatibility reasons, and I no longer have access to that configuration.

Is there any advantage to having a 'release' with different binaries/MSI compared to 1.0.1, or is it just a new release in GitHub that you need?

**Comment by mawiseman** [comment]
I need the new release with installer so that the chocolatey package can install the latest version with the updated details.

Multiple installers would be ok.

I would just reference the latest installer initially and if people still need IIS 7 add a new package then

**Comment by mawiseman** [comment]
saying that... the pullrequest you have just approved is looking for

- https://github.com/richardszalay/iishosts/releases/download/v1.0.2/iishosts_1.0.2_x86.msi
- https://github.com/richardszalay/iishosts/releases/download/v1.0.2/iishosts_1.0.2_x64.msi

Once they exist i can upload the latest chocolatey file

**Comment by richardszalay** [comment]
As an update, I'm no longer able to build the solution. In order to continue to target IIS 7+, it needs to be run on a build machine that has IIS 7 installed which is obviously problematic in 2019.

There are two choices from here:
* Target IIS10+ and release as 2.0
* Re-release 1.0.1 via Chocolatey

Do you have a preference either way?

**Pull request merged**
